
-- name: HANA_CLIENTES
SELECT * 
FROM "MOBO_PRODUCTIVO"."CLIENTESBIR"
WHERE "CardCode" IS NOT NULL
----WHERE "CardCode" IN ('CCAD0981', 'CCAD0980')

UNION

SELECT * 
FROM "SBO_FITMEX"."CLIENTESBIR"
WHERE "CardCode" IS NOT NULL
----WHERE "CardCode" IN ('CCAD0981', 'CCAD0980')



-- name: SQL_CLIENTES
SELECT * FROM MOBODW_STG..stage_clientes_py


